[package]
name = "maps"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
osmpbfreader = "0.16.1"
plotters = "0.3.6"
resvg = "0.42.0"
serde = { version = "1.0.204", features = ["derive"] }
usvg = "0.42.0"
